# Generated by Django 2.1.7 on 2019-03-31 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('lesson1', models.CharField(blank=True, max_length=40, null=True)),
                ('time1', models.CharField(blank=True, max_length=15, null=True)),
                ('teacher1', models.CharField(blank=True, max_length=35, null=True)),
                ('lesson2', models.CharField(blank=True, max_length=40, null=True)),
                ('time2', models.CharField(blank=True, max_length=15, null=True)),
                ('teacher2', models.CharField(blank=True, max_length=35, null=True)),
                ('lesson3', models.CharField(blank=True, max_length=40, null=True)),
                ('time3', models.CharField(blank=True, max_length=15, null=True)),
                ('teacher3', models.CharField(blank=True, max_length=35, null=True)),
                ('lesson4', models.CharField(blank=True, max_length=40, null=True)),
                ('time4', models.CharField(blank=True, max_length=15, null=True)),
                ('teacher4', models.CharField(blank=True, max_length=35, null=True)),
                ('lesson5', models.CharField(blank=True, max_length=40, null=True)),
                ('time5', models.CharField(blank=True, max_length=15, null=True)),
                ('teacher5', models.CharField(blank=True, max_length=35, null=True)),
                ('govoritpolina', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
